name: Reportar Bug Produccion
description: Formulario  Reportar Bug en produccion
title: "BUG#PRODUCCION#  "
labels: ["bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Describa el error     
  - type: textarea
    id: descripcion
    attributes:
      label: Una descripción clara y concisa de lo que es el error.
      options:
        validations: 
          required: true           
  - type: textarea
    id: reproducir
    attributes:
      label: Pasos para reproducir el comportamiento
      description:  |
                   1. Ir a '...'
                   2. Haga clic en '....'
                   3. Desplácese hacia abajo hasta '....'
                   4. Ver error
    validations: 
     required: true        
  - type: textarea
    id: Comportamientoesperado
    attributes:
      label: Comportamiento esperado
      description: Una descripción clara y concisa de lo que esperaba que sucediera.
    validations:
      required: false     
  - type: textarea
    id: Informacionadicional
    attributes:
      label: Informacion adicional
      description: |
                  - SO: [p. ej. iOS]
                  - Navegador [p. ej. cromo, safari]
                  - Versión [p. ej. 22]
                  - Dispositivo: [p. ej. iphone 6]
                  - SO: [p. ej. iOS8.1]
                  - Navegador [p. ej. navegador de valores, safari]
                  - Versión [p. ej. 22]
    validations:
      required: false       
  - type: input
    id: ContextoadicionaL
    attributes:
      label: Contexto adicionaL
      description: Agregue cualquier otro contexto sobre el problema aquí.
    validations:
      required: false   
  - type: dropdown
    id: PersonaDeContacto
    attributes:
      label: Persona de contacto
      multiple: false
      description: Quien reporta el Bug
      options:
        - TEO
        - FANNY
    validations:
      required: true     
  - type: dropdown
    id: Software
    attributes:
      label: Software
      multiple: false
      options:
        - FACTURADOR WEB
        - PASAJEROS WEB
        - ENCOMIENDAS WEB
        - FACTURADOR ESCRITORIO
        - COLEGIOS ESCRITORIO
        - RESTAURANTES ESCRITORIO
        - PASAJEROS ESCRITORIO
        - ENCOMIENDAS ESCRITORIO

