name: 📁 Caracter invalido XML
description: Formulario para Reportar Caracteres invalidos 
title: "BUG#PRODUCCION"
labels: ["bug: production"]
body: 


  - type: input
    id: documento
    attributes:
      label: Tipo/Serie/Numero de comprobante.
      placeholder: 01/F001/1541
    validations:
      required: true
      
  - type: input
    id: campo
    attributes:
      label: Campo/Columna carácter invalido
      placeholder: Ingrese el campo o la columna donde se genera el error.
    validations:
      required: true

  - type: input
    id: xml
    attributes:
      label: XML del comprobante.
      placeholder: Agregue xml del comprobante.
    validations:
      required: true

  - type: input
    id: backup
    attributes:
      label: Copia de la base de datos
      placeholder: Agregue una copia de la base de datos.
    validations:
      required: true


      
