name: Reportar Bug Produccion
description: Formulario  Reportar Bug en produccion
title: "BUG#PRODUCCION#"
labels: ["invalid"]
body: 

  - type: dropdown
    id: Software
    attributes:
      label: Software
      multiple: false
      options:		
      - Contabilidad Escritorio
      - Facturador Escritorio
      - Colegios Escritorio
      - Restaurantes Escritorio
      - Pasajeros Escritorio
      - Encomiendas Escritorio        
      - Facturador Web
      - Pasajeros Web
      - Encomiendas Web
                
    validations:
      required: true      
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción.
      placeholder:  Una descripción clara y concisa de lo que es el error. 
    validations: 
      required: true
  - type: textarea
    id: reproducir
    attributes:
      label: Pasos para reproducir el comportamiento
      placeholder:  |
                   1. Ir a '...'
                   2. Haga clic en '....'
                   3. Desplácese hacia abajo hasta '....'
                   4. Ver error
    validations: 
      required: false
  - type: textarea
    id: Comportamientoesperado
    attributes:
      label: Comportamiento esperado      
      placeholder: Una descripción clara y concisa de lo que esperaba que sucediera.     
    validations:
      required: false
  - type: textarea
    id: Informacionadicional
    attributes:
      label: Informacion adicional
      placeholder: |
                  - SO: [p. ej. iOS]
                  - Navegador [p. ej. cromo, safari]
                  - Versión [p. ej. 22]
                  - Dispositivo: [p. ej. iphone 6]
                  - SO: [p. ej. iOS8.1]
                  - Navegador [p. ej. navegador de valores, safari]
                  - Versión [p. ej. 22]
    validations:
      required: false
  - type: input
    id: ContextoadicionaL
    attributes:
      label: Contexto adicionaL
      placeholder: Agregue cualquier otro contexto sobre el problema aquí.
    validations:
      required: false
      
