name:  Sugiera una mejora para este proyecto
description: Formulario para sugerir  una idea, una mejora, mejorar una caracter铆stica existente o una posible nueva funci贸n para este proyecto.
title: "MEJORA#"
labels: ["enhancement pending review"]
body: 

  - type: dropdown
    id: Software
    attributes:
      label: Software 
      multiple: false
      options:		
      - Contabilidad Escritorio
      - Facturador Escritorio
      - Colegios Escritorio
      - Restaurantes Escritorio
      - Pasajeros Escritorio
      - Encomiendas Escritorio        
      - Facturador Web
      - Pasajeros Web
      - Encomiendas Web
                
    validations:
      required: true      
  - type: textarea
    id: descripcion
    attributes:
      label: Descripci贸n.
      placeholder:  Proporcione una descripci贸n detallada del cambio o adici贸n que est谩 proponiendo.
    validations: 
      required: true
  - type: textarea
    id: contexto
    attributes:
      label: Contexto
      placeholder:  |
                   - 驴Por qu茅 es importante este cambio para el cliente CIBERCONT o usted?.
                   - 驴C贸mo puede beneficiar a otros clientes?.
    validations: 
      required: true
  - type: textarea
    id: posibleImplementacion
    attributes:
      label: Posible Implementaci贸n
      placeholder: sugiera una idea para implementar la adici贸n o el cambio.
    validations:
      required: false


  - type: textarea
    id: ContextoadicionaL
    attributes:
      label: Contexto adicionaL
      placeholder: Agregue cualquier otro contexto aqu铆.
    validations:
      required: false
      
