name: 🆕 Sugiera una  mejora para este proyecto
description: Formulario para sugerir una mejora que está relacionada con un 💢 problema.
title: "MEJORA#"
labels: ["enhancement pending review"]
body: 

  - type: dropdown
    id: Software
    attributes:
      label: Software 
      multiple: false
      options:		
      - Contabilidad Escritorio
      - Facturador Escritorio
      - Colegios Escritorio
      - Restaurantes Escritorio
      - Pasajeros Escritorio
      - Encomiendas Escritorio        
      - Facturador Web
      - Pasajeros Web
      - Encomiendas Web
                
    validations:
      required: true      
  - type: textarea
    id: error
    attributes:
      label: Problematica      
      placeholder:  ¿Su solicitud de mejora está relacionada con un problema? Por favor describa el problema.
                    Una descripción clara y concisa de cuál es el problema. Ejem. Siempre me siento frustrado cuando [...] 
    validations: 
      required: true
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción.
      placeholder:  Proporcione una descripción detallada del cambio o adición que está proponiendo.
    validations: 
      required: true

  - type: textarea
    id: posibleImplementacion
    attributes:
      label: Posible Implementación
      placeholder: sugiera una idea para implementar la adición o el cambio.
    validations:
      required: false


  - type: textarea
    id: ContextoadicionaL
    attributes:
      label: Contexto adicionaL
      placeholder: Agregue cualquier otro contexto aquí.
    validations:
      required: false
      
