name:  Sugiera una mejora para este proyecto
description: Formulario para sugerir  una idea, una mejora,Mejorar una caracter铆stica existente o una posible nueva funci贸n para este proyecto.
title: "MEJORA#"
labels: ["enhancement pending review"]
body: 

  - type: dropdown
    id: Software
    attributes:
      label: Software 
      multiple: false
      options:		
      - Contabilidad Escritorio
      - Facturador Escritorio
      - Colegios Escritorio
      - Restaurantes Escritorio
      - Pasajeros Escritorio
      - Encomiendas Escritorio        
      - Facturador Web
      - Pasajeros Web
      - Encomiendas Web
                
    validations:
      required: true      
  - type: textarea
    id: descripcion
    attributes:
      label: Descripci贸n.
      placeholder:  Proporcione una descripci贸n detallada del cambio o adici贸n que est谩 proponiendo 
    validations: 
      required: true
  - type: textarea
    id: contexto
    attributes:
      label: Contexto
      placeholder:  |
                   - 驴Por qu茅 es importante este cambio para el cliente CIBERCONT o usted?
                   - 驴C贸mo puede beneficiar a otros clientes?
    validations: 
      required: true
  - type: textarea
    id: Comportamientoesperado
    attributes:
      label: Comportamiento esperado      
      placeholder: Una descripci贸n clara y concisa de lo que esperaba que sucediera.     
    validations:
      required: true

  - type: textarea
    id: Screenshots
    attributes:
      label: Screenshots - Media      
      placeholder: Agregue capturas de pantalla o videos para ayudar a explicar su problema.
    validations:
      required: false


  - type: input
    id: backup
    attributes:
      label: Copia de la base de datos
      placeholder: Agregue una copia de la base de datos.
    validations:
      required: false

      
  - type: textarea
    id: Informacionadicional
    attributes:
      label: Informacion adicional
      placeholder: |
                  - SO: [p. ej. iOS]
                  - Navegador [p. ej. cromo, safari]
                  - Versi贸n [p. ej. 22]
                  - Dispositivo: [p. ej. iphone 6]
                  - SO: [p. ej. iOS8.1]
                  - Navegador [p. ej. navegador de valores, safari]
                  - Versi贸n [p. ej. 22]
    validations:
      required: false
  - type: input
    id: ContextoadicionaL
    attributes:
      label: Contexto adicionaL
      placeholder: Agregue cualquier otro contexto sobre el problema aqu铆.
    validations:
      required: false
      
